2022-12-02 22:53:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIOS" not found; SQL statement:
INSERT INTO USUARIOS (`carnet`, `nombre`, `correo`, `contraseña`, `rol`, `carrera`) VALUES (2167317, 'ejemplo-nombre', 'ejemplo-correo@mail.escuelaing.edu.co','123', 'usuario', 'Ingenieria de sistemas') [42102-191]
2022-12-02 22:53:57 jdbc[6]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at biblioteca.tests.ServicesJUnitTest.getConnection(ServicesJUnitTest.java:44)
	at biblioteca.tests.ServicesJUnitTest.clearDB(ServicesJUnitTest.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 39 more
2022-12-02 22:56:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIOS" not found; SQL statement:
INSERT INTO USUARIOS (`carnet`, `nombre`, `correo`, `contraseña`, `rol`, `carrera`) VALUES (2167317, 'ejemplo-nombre', 'ejemplo-correo@mail.escuelaing.edu.co','123', 'usuario', 'Ingenieria de sistemas') [42102-191]
2022-12-02 22:59:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIOS" not found; SQL statement:
INSERT INTO USUARIOS (`carnet`, `nombre`, `correo`, `contraseña`, `rol`, `carrera`) VALUES (2167317, 'ejemplo-nombre', 'ejemplo-correo@mail.escuelaing.edu.co','123', 'usuario', 'Ingenieria de sistemas') [42102-191]
2022-12-02 23:18:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:18:02 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:18:02 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:19:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE FROM 'RECURSOS'[*] "; expected "identifier"; SQL statement:
delete from 'RECURSOS' [42001-191]
2022-12-02 23:19:44 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE FROM 'RECURSOS'[*] "; expected "identifier"; SQL statement:
delete from 'RECURSOS' [42001-191]
2022-12-02 23:19:44 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE FROM 'RECURSOS'[*] "; expected "identifier"; SQL statement:
delete from 'RECURSOS' [42001-191]
2022-12-02 23:20:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:20:58 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:20:58 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:22:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:22:01 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
2022-12-02 23:22:01 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE ""RECURSOS"" (""ID"" INT(11) NOT NULL AUTO_INCREMENT,""NOMBRE"" VARCHAR(45) NOT NULL,""UBICACION"" VARCHAR(45) NOT NULL,""TIPO"" VARCHAR(45) NOT NULL,""CAPACIDAD"" INT(11) NOT NULL,""DESCRIPCION"" VARCHAR(45) NOT NULL,""DISPONIBLE"" INT(2) NOT NULL, PRIMARY KEY (""ID"",""NOMBRE"") ENGINE[*]=INNODB; "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE `RECURSOS` (`id` int(11) NOT NULL AUTO_INCREMENT,`nombre` varchar(45) NOT NULL,`ubicacion` varchar(45) NOT NULL,`tipo` varchar(45) NOT NULL,`capacidad` int(11) NOT NULL,`descripcion` varchar(45) NOT NULL,`disponible` int(2) NOT NULL, PRIMARY KEY (`id`,`nombre`) ENGINE=InnoDB; [42001-191]
